/* 
Name: Ethan Huynh
BlazerID: ethuynh
Assignment: Bonus Homework

To compile: "make" or
             gcc -Wall -o bonusHW bonusHW.c

To execute: "make run" or
            ./bonusHW
*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h> // fork, pipe, read, write, close
#include <sys/types.h> // pid_t
#include <sys/wait.h>
#include <pthread.h>
#include <time.h>
#include <string.h>

// Constants
#define NUM_PRODUCERS 10
#define NUM_CONSUMERS 20
#define NUM_PER_PRODUCER 500 // generates 500 numbers
#define NUM_PER_CONSUMER 250 // reads 250 numbers
#define RAND_MAX_VALUE 1000 // only numbers from 0 to 1000

// Total numbers: 10 * 500 = 5000
// Consumers: 20 * 250 = 5000

// pipefd[0] = read end
// pipefd[1] = write end

// Global pipe file descriptors
int pipefd[2];

// Mutexes for synchronization
pthread_mutex_t write_mutex = PTHREAD_MUTEX_INITIALIZER; // writes to pipe
pthread_mutex_t read_mutex  = PTHREAD_MUTEX_INITIALIZER; // reads from pipe
pthread_mutex_t print_mutex = PTHREAD_MUTEX_INITIALIZER; // printf output

// Consumer sums (shared in child)
long consumer_sums[NUM_CONSUMERS];

// Producer thread function
void *producer_thread(void *arg) {
    int id = (int)(long)arg; // thread ID (0-9)

    // seed random using time + id
    srand((unsigned int)(time(NULL) ^ id));

    // track uniqueness per thread using a simple array
    // used[i] == 1 means value i has already been generated by this thread
    int used[RAND_MAX_VALUE + 1];
    memset(used, 0, sizeof(used));

    int count = 0;

    while (count < NUM_PER_PRODUCER) {
        int value = rand() % (RAND_MAX_VALUE + 1); // 0-1000

        if (!used[value]) {
            used[value] = 1;
            count++;

            // write value to pipe
            pthread_mutex_lock(&write_mutex);
            ssize_t w = write(pipefd[1], &value, sizeof(int));
            pthread_mutex_unlock(&write_mutex);

            if (w != sizeof(int)) {
                pthread_mutex_lock(&print_mutex);
                perror("write");
                pthread_mutex_unlock(&print_mutex);
                break;
            }

            if (count % 50 == 0) {
                pthread_mutex_lock(&print_mutex);
                printf("Producer %d: wrote %d/%d numbers\n",
                       id, count, NUM_PER_PRODUCER);
                pthread_mutex_unlock(&print_mutex);
            }
        }
    }

    pthread_mutex_lock(&print_mutex);
    printf("Producer %d: finished generating %d unique numbers\n",
           id, NUM_PER_PRODUCER);
    pthread_mutex_unlock(&print_mutex);

    return NULL;
}

// Consumer thread function
void *consumer_thread(void *arg) {
    int id = (int)(long)arg; // thread ID (0-19)
    long sum = 0;

    for (int i = 0; i < NUM_PER_CONSUMER; i++) {
        int value;

        // protect read from pipe
        pthread_mutex_lock(&read_mutex);
        ssize_t r = read(pipefd[0], &value, sizeof(int));
        pthread_mutex_unlock(&read_mutex);

        if (r != sizeof(int)) {
            pthread_mutex_lock(&print_mutex);
            perror("read");
            pthread_mutex_unlock(&print_mutex);
            break;
        }

        sum += value;
    }

    consumer_sums[id] = sum;

    pthread_mutex_lock(&print_mutex);
    printf("Consumer %d: sum of my %d numbers = %ld\n",
           id, NUM_PER_CONSUMER, sum);
    pthread_mutex_unlock(&print_mutex);

    return NULL;
}

// Child process logic
void run_child() {
    // read end of pipe
    close(pipefd[1]);

    // initialize consumer sums
    for (int i = 0; i < NUM_CONSUMERS; i++) {
        consumer_sums[i] = 0;
    }

    pthread_t consumers[NUM_CONSUMERS];

    // create consumer threads
    for (int i = 0; i < NUM_CONSUMERS; i++) {
        pthread_create(&consumers[i], NULL, consumer_thread, (void *)(long)i);
    }

    // wait for all consumers to finish
    for (int i = 0; i < NUM_CONSUMERS; i++) {
        pthread_join(consumers[i], NULL);
    }

    // compute average of sums
    long total = 0;
    for (int i = 0; i < NUM_CONSUMERS; i++) {
        total += consumer_sums[i];
    }

    double average = (double)total / (double)NUM_CONSUMERS;

    // print average to stdout (user can redirect to file)
    printf("Average of consumer sums = %.2f\n", average);

    // close read end
    close(pipefd[0]);

    exit(0);
}

// Parent process logic
void run_parent(pid_t child_pid) {
    // write end of pipe
    close(pipefd[0]);

    pthread_t producers[NUM_PRODUCERS];

    // create producer threads
    for (int i = 0; i < NUM_PRODUCERS; i++) {
        pthread_create(&producers[i], NULL, producer_thread, (void *)(long)i);
    }

    // wait for producers
    for (int i = 0; i < NUM_PRODUCERS; i++) {
        pthread_join(producers[i], NULL);
    }

    pthread_mutex_lock(&print_mutex);
    printf("Parent: all producer threads finished\n");
    pthread_mutex_unlock(&print_mutex);

    // close write end so child sees EOF eventually
    close(pipefd[1]);

    // wait for child process
    int status;
    waitpid(child_pid, &status, 0);

    if (WIFEXITED(status)) {
        pthread_mutex_lock(&print_mutex);
        printf("Parent: child exited with status %d\n", WEXITSTATUS(status));
        pthread_mutex_unlock(&print_mutex);
    } else {
        pthread_mutex_lock(&print_mutex);
        printf("Parent: child did not terminate normally\n");
        pthread_mutex_unlock(&print_mutex);
    }
}

// main()
int main(int argc, char *argv[]) {
    // create pipe for IPC between parent and child
    if (pipe(pipefd) == -1) {
        perror("pipe");
        exit(1);
    }

    pid_t pid = fork();

    if (pid < 0) {
        perror("fork");
        exit(1);
    } else if (pid == 0) {
        // child process
        run_child();
    } else {
        // parent process
        run_parent(pid);
    }

    return 0;
}
